# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ix_ntp module
"""


class NtpArgs(object):  # pylint: disable=R0903
    """The arg spec for the ix_ntp module
    """

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "address_families": {
                    "type": "str",
                    "choices": ["ipv4", "ipv6"],
                    "options": {
                        "enable": {"type": "bool"},
                        "access_list": {"type": "str"},
                    },
                },
                "master": {"default": 8, "type": "int"},
                "retry": {"type": "int"},
                "servers": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "address": {"type": "str"},
                        "priority": {"default": 1, "type": "int"},
                        "retry": {"default": 0, "type": "int"},
                        "source": {"type": "str"},
                        "timeout": {"default": 64, "type": "int"},
                        "version": {"default": 3, "type": "int"},
                    },
                },
                "source": {"type": "str"},
                "vrf": {"type": "str"},
                "interval": {"type": "int"},
            },
        }
    }  # pylint: disable=C0301
