namespace: rucdev
name: ix
version: 0.1.2
readme: README.md
authors:
  - Yushi Takeda
description: Ansible collection for NEC IX series
license_file: LICENSE
tags: [nec, ix, networking]
dependencies:
  "ansible.netcommon": ">=2.5.1"
repository: https://github.com/Rucdev/ix_ansible.git
homepage: https://github.com/Rucdev/ix_ansible
issues: https://github.com/Rucdev/ix_ansible/issues
build_ignore: [.venv, example]
