# -*- coding: utf-8 -*-
# Copyright 2025 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ix_ospfv3 module
"""


class Ospfv3Args(object):  # pylint: disable=R0903
    """The arg spec for the ix_ospfv3 module
    """

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "processes": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "process_id": {"required": True, "type": "int"},
                        "areas": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "area_id": {"type": "str"},
                                "default_cost": {"type": "int"},
                                "ranges": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "address": {"type": "str"},
                                        "advertise": {
                                            "type": "bool",
                                            "default": True,
                                        },
                                    },
                                },
                                "stub": {
                                    "type": "dict",
                                    "options": {
                                        "set": {"type": "bool"},
                                        "no_summary": {"type": "bool"},
                                    },
                                },
                            },
                        },
                        "distance": {
                            "type": "dict",
                            "options": {
                                "external": {"type": "int", "default": 110},
                                "inter_area": {"type": "int", "default": 110},
                                "intra_area": {"type": "int", "default": 110},
                            },
                        },
                        "network": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "interface": {"type": "str"},
                                "area": {"type": "str"},
                            },
                        },
                        "originate_default": {
                            "type": "dict",
                            "options": {
                                "metric": {"type": "int", "default": 1},
                                "metric_type": {"type": "int", "default": 2},
                                "route_map": {"type": "str"},
                                "tag": {"type": "int", "default": 0},
                            },
                        },
                        "passive_interfaces": {"type": "list", "elements": "str"},
                        "router_id": {"type": "str"},
                        "timers": {
                            "type": "dict",
                            "options": {
                                "delay": {"type": "int", "default": 5},
                                "hold": {"type": "int", "default": 10},
                            },
                        },
                    },
                }
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "gathered",
                "rendered",
                "parsed",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
