__metaclass__ = type
#
# -*- coding: utf-8 -*-
# Copyright 2024 AP Communications
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ix_static_routes module
"""


class Static_routesArgs(object):  # pylint: disable=R0903
    """The arg spec for the ix_static_routes module"""

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "ipv4": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "address": {"type": "str"},
                        "gateway": {"type": "str"},
                    },
                },
                "vrf": {"type": "str"},
            },
        }
    }  # pylint: disable=C0301
