# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ix_static_routes module
"""


class Static_routesArgs(object):  # pylint: disable=R0903
    """The arg spec for the ix_static_routes module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "address_families": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "afi": {
                            "type": "str",
                            "choices": ["ipv4", "ipv6"],
                            "required": True,
                        },
                        "routes": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "dest": {"type": "str", "required": True},
                                "next_hops": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "forward_router_address": {"type": "str"},
                                        "interface": {"type": "str"},
                                        "dhcp": {"type": "bool"},
                                        "connected": {"type": "bool"},
                                        "distance": {"type": "int"},
                                        "metric": {"type": "int"},
                                        "tag": {"type": "int"},
                                        "ra": {"type": "bool"},
                                    },
                                },
                            },
                        },
                    },
                },
                "vrf": {"type": "str"},
            },
        },
        "state": {
            "choices": [
                "merged",
                "replaced",
                "overridden",
                "deleted",
                "rendered",
                "gathered",
                "purged",
                "parsed",
            ],
            "default": "merged",
            "type": "str",
        },
    }  # pylint: disable=C0301
