# -*- coding: utf-8 -*-
# Copyright 2024 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ix_ospfv2 module
"""


class Ospfv2Args(object):  # pylint: disable=R0903
    """The arg spec for the ix_ospfv2 module
    """

    argument_spec = {
        "config": {
            "type": "dict",
            "options": {
                "processes": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "process_id": {"required": True, "type": "int"},
                        "areas": {
                            "type": "list",
                            "elements": "dict",
                            "options": {
                                "area_id": {"type": "str"},
                                "default_cost": {"type": "int"},
                                "nssa": {
                                    "type": "dict",
                                    "options": {
                                        "no_summary": {"type": "bool"},
                                        "translate": {"type": "bool"},
                                        "stability_interval": {"type": "int"},
                                        "default_metric": {"type": "int"},
                                        "default_metric_type": {
                                            "type": "int",
                                            "choices": [1, 2],
                                        },
                                    },
                                },
                                "ranges": {
                                    "type": "list",
                                    "elements": "dict",
                                    "options": {
                                        "address": {"type": "str"},
                                        "advertise": {"type": "bool"},
                                    },
                                },
                                "stub": {
                                    "type": "dict",
                                    "options": {"no_summary": {"type": "bool"}},
                                },
                                "virtual-link": {
                                    "type": "dict",
                                    "options": {
                                        "authentication": {
                                            "type": "str",
                                            "default": "text",
                                            "choices": [
                                                "text",
                                                "message-digest",
                                                "null",
                                            ],
                                        },
                                        "authentication_key": {"type": "str"},
                                        "message_digest_key": {"type": "str"},
                                        "dead_interval": {"type": "int"},
                                        "hello_interval": {"type": "int"},
                                        "retransmit_interval": {"type": "int"},
                                        "transmit_delay": {"type": "int"},
                                    },
                                },
                            },
                        },
                        "compatible": {
                            "type": "dict",
                            "options": {"rfc1583": {"type": "bool"}},
                        },
                        "default_metric": {"type": "int"},
                        "distance": {
                            "type": "dict",
                            "options": {
                                "external": {"type": "int"},
                                "inter_area": {"type": "int"},
                                "intra": {"type": "int"},
                                "nssa_external": {"type": "int"},
                            },
                        },
                        "distribute_list": {
                            "type": "dict",
                            "options": {
                                "prefix": {"type": "str"},
                                "route_map": {"type": "str"},
                            },
                        },
                        "network": {
                            "type": "list",
                            "elements": "dice",
                            "options": {
                                "address": {"type": "str"},
                                "area": {"type": "str"},
                            },
                        },
                        "passive_interface": {"type": "str"},
                        "rib": {
                            "type": "dict",
                            "options": {"max_entries": {"type": "int"}},
                        },
                        "timers": {
                            "type": "dict",
                            "options": {
                                "delay": {"type": "int"},
                                "hold": {"type": "int"},
                            },
                        },
                    },
                }
            },
        },
        "state": {"type": "str", "default": "merged"},
    }  # pylint: disable=C0301
